# Generated by Django 4.0.4 on 2022-05-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('ClassroomId', models.AutoField(primary_key=True, serialize=False)),
                ('ClassroomNumber', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='PhotoFileName',
            new_name='Preferencies',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='DateOfJoining',
        ),
    ]
