# Generated by Django 4.0.4 on 2022-05-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0002_classroom_rename_photofilename_teachers_preferencies_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
