# Generated by Django 4.0.4 on 2022-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0003_rename_departments_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupId', models.AutoField(primary_key=True, serialize=False)),
                ('GroupNumber', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
            ],
        ),
    ]
