# Generated by Django 4.0.4 on 2022-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0004_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfClass', models.CharField(max_length=500)),
                ('Capacity', models.CharField(max_length=500)),
                ('Number', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstClassStarts', models.CharField(max_length=500)),
                ('ClassDuration', models.CharField(max_length=500)),
                ('ShortBrakeDuration', models.CharField(max_length=500)),
                ('LargeBrakeDuration', models.CharField(max_length=500)),
                ('StudyDaysInWeek', models.CharField(max_length=500)),
                ('StudyDaysInWeekForStudents', models.CharField(max_length=500)),
                ('StudyDaysInWeekForTeachers', models.CharField(max_length=500)),
                ('ClassesPerDay', models.CharField(max_length=500)),
                ('ClassesPerDayStudents', models.CharField(max_length=500)),
                ('ClassesPerDayTeachers', models.CharField(max_length=500)),
                ('LunchBrake', models.CharField(max_length=500)),
                ('Gaps', models.CharField(max_length=500)),
                ('ClassroomFillness', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty', models.CharField(max_length=500)),
                ('EducationalProgram', models.CharField(max_length=500)),
                ('Specialization', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Faculty', models.CharField(max_length=500)),
                ('EducationalProgram', models.CharField(max_length=500)),
                ('Specialization', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=500)),
                ('Teacher', models.CharField(max_length=500)),
                ('TypeOfClass', models.CharField(max_length=500)),
                ('Auditory', models.CharField(max_length=500)),
                ('Groups', models.CharField(max_length=500)),
                ('Day', models.CharField(max_length=500)),
                ('ClassNumber', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty', models.CharField(max_length=500)),
                ('EducationalProgram', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=500)),
                ('Day', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=500)),
                ('Teacher', models.CharField(max_length=500)),
                ('Auditory', models.CharField(max_length=500)),
                ('Groups', models.CharField(max_length=500)),
                ('NumberOfClass', models.CharField(max_length=500)),
                ('TypeOfClass', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Faculty', models.CharField(max_length=500)),
                ('EducationalProgram', models.CharField(max_length=500)),
                ('Specialization', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=500)),
                ('Semester', models.CharField(max_length=500)),
                ('Teacher', models.CharField(max_length=500)),
                ('TypeOfClass', models.CharField(max_length=500)),
                ('Auditory', models.CharField(max_length=500)),
                ('Groups', models.CharField(max_length=500)),
                ('Day', models.CharField(max_length=500)),
                ('ClassNumber', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=500)),
                ('Number', models.CharField(max_length=500)),
                ('AmountOfStudents', models.CharField(max_length=500)),
                ('YearOfStudy', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('Semesters', models.CharField(max_length=500)),
                ('TypeOfClass', models.CharField(max_length=500)),
                ('Frequency', models.CharField(max_length=500)),
                ('Teacher', models.CharField(max_length=500)),
                ('AmountOfGroups', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('DaysCanWork', models.CharField(max_length=500)),
                ('DaysWantWork', models.CharField(max_length=500)),
                ('Weight', models.CharField(max_length=500)),
            ],
        ),
    ]
