# Generated by Django 4.0.4 on 2022-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0005_auditory_constraints_educationalprograms_entries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
