# Generated by Django 4.0.4 on 2022-05-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0006_alter_auditory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditory',
            old_name='id',
            new_name='AuditoryId',
        ),
    ]
