# Generated by Django 4.0.4 on 2022-05-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0007_rename_id_auditory_auditoryid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditory',
        ),
    ]
