# Generated by Django 4.0.4 on 2022-05-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0008_delete_auditory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('AuditoryId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeOfClass', models.CharField(max_length=500)),
                ('Capacity', models.CharField(max_length=500)),
                ('Number', models.CharField(max_length=500)),
            ],
        ),
    ]
