# Generated by Django 4.0.4 on 2022-05-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0009_auditory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auditory',
            new_name='Auditories',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
