# Generated by Django 4.0.4 on 2022-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0010_rename_auditory_auditories_delete_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditories',
            name='AuditoryId',
        ),
        migrations.AddField(
            model_name='auditories',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
