# Generated by Django 4.0.4 on 2022-05-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0011_remove_auditories_auditoryid_auditories_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
    ]
