# Generated by Django 4.0.4 on 2022-05-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableApp', '0012_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherId', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('Preferencies', models.CharField(max_length=500)),
            ],
        ),
    ]
